
import demos.nn.KohonenPanel;
import demos.nn.PerceptronPanel;
import demos.nn.CompetitivePanel;
import demos.nn.MPLPanel;
import demos.nn.LVQPanel;
import demos.nn.RBFPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Examples.java
 *
 * Created on May 3, 2009, 12:15:53 PM
 */

/**
 *
 * @author kronenthaler
 */
public class Examples extends javax.swing.JFrame {
	/** Creates new form Examples */
    public Examples() {
        initComponents();

		
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        fuzzyPanel1 = new demos.fuzzy.FuzzyPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        binaryPanel1 = new demos.genetic.BinaryPanel();
        permutation1 = new demos.genetic.Permutation();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        perceptronPanel1 = new demos.nn.PerceptronPanel();
        mPLPanel1 = new demos.nn.MPLPanel();
        rBFPanel1 = new demos.nn.RBFPanel();
        lVQPanel1 = new demos.nn.LVQPanel();
        kohonenPanel1 = new demos.nn.KohonenPanel();
        competitivePanel1 = new demos.nn.CompetitivePanel();
        hebbPanel1 = new demos.nn.HopfieldPanel();
        treesPanel1 = new demos.trees.TreesPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        bFSPanel1 = new demos.search.BFSPanel();
        aStarPanel1 = new demos.search.AStarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examples libai");

        jTabbedPane2.addTab("Fuzzy", fuzzyPanel1);

        jTabbedPane3.addTab("Binary", binaryPanel1);
        jTabbedPane3.addTab("Permutation", permutation1);

        jTabbedPane2.addTab("Genetic", jTabbedPane3);

        jTabbedPane1.addTab("Adaline", perceptronPanel1);
        jTabbedPane1.addTab("MLP", mPLPanel1);
        jTabbedPane1.addTab("RBF", rBFPanel1);
        jTabbedPane1.addTab("LVQ", lVQPanel1);
        jTabbedPane1.addTab("Kohonen", kohonenPanel1);
        jTabbedPane1.addTab("Competitive", competitivePanel1);
        jTabbedPane1.addTab("Hopfield", hebbPanel1);

        jTabbedPane2.addTab("Neural Networks", jTabbedPane1);

        org.jdesktop.layout.GroupLayout treesPanel1Layout = new org.jdesktop.layout.GroupLayout(treesPanel1);
        treesPanel1.setLayout(treesPanel1Layout);
        treesPanel1Layout.setHorizontalGroup(
            treesPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 634, Short.MAX_VALUE)
        );
        treesPanel1Layout.setVerticalGroup(
            treesPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 491, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Decision Trees", treesPanel1);

        jTabbedPane4.addTab("BFS", bFSPanel1);
        jTabbedPane4.addTab("A*", aStarPanel1);

        jTabbedPane2.addTab("Search", jTabbedPane4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private demos.search.AStarPanel aStarPanel1;
    private demos.search.BFSPanel bFSPanel1;
    private demos.genetic.BinaryPanel binaryPanel1;
    private demos.nn.CompetitivePanel competitivePanel1;
    private demos.fuzzy.FuzzyPanel fuzzyPanel1;
    private demos.nn.HopfieldPanel hebbPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private demos.nn.KohonenPanel kohonenPanel1;
    private demos.nn.LVQPanel lVQPanel1;
    private demos.nn.MPLPanel mPLPanel1;
    private demos.nn.PerceptronPanel perceptronPanel1;
    private demos.genetic.Permutation permutation1;
    private demos.nn.RBFPanel rBFPanel1;
    private demos.trees.TreesPanel treesPanel1;
    // End of variables declaration//GEN-END:variables

}
